from enum import StrEnum


class EventType(StrEnum):
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_STOPPED = "SESSION_STOPPED"
    METER_VALUES_RECEIVED = "METER_VALUES_RECEIVED"
    CHARGER_STATUS_CHANGED = "CHARGER_STATUS_CHANGED"
    CHARGER_CONNECTED = "CHARGER_CONNECTED"
    CHARGER_DISCONNECTED = "CHARGER_DISCONNECTED"
    AUTH_REQUESTED = "AUTH_REQUESTED"
    ALARM_RAISED = "ALARM_RAISED"
    DIAGNOSTICS_STATUS_CHANGED = "DIAGNOSTICS_STATUS_CHANGED"
    FIRMWARE_STATUS_CHANGED = "FIRMWARE_STATUS_CHANGED"
